version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=pgdsba
      - MYSQL_ROOT_PASSWORD=hello123
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local